# Sample config file for WolfAdmin. Adjust to your needs.

# See https://dev.timosmit.com/wolfadmin/
#     https://dev.timosmit.com/wolfadmin/configuration.html

[main]
# uncomment if you need to override these settings
# os = "unix"
# standalone = 1
debug = 0

[db]
type = "sqlite3"
file = "wolfadmin.db"
# the settings below are only used for type 'mysql', uncomment if needed
# hostname = "localhost"
# port = 3306
# database = "wolfadmin"
# username = "wolfadmin"
# password = "suchasecret"

[logs]
chat = "chat.log"
admin = "admin.log"

[omnibot]
minbots = 5
maxbots = 6

[admin]
history = 1
maxrenames = 80

[balancer]
mindif = 2
maxdif = 5
selection = 0
interval = 30

[game]
announcerevives = 0

[voting]
timeout = 0
restricted = []

[banners]
file = "tomfiles/banners.toml"
interval = 120
random = 1
area = 3

[rules]

[greetings]
file = ""
area = 3
bots = 1

[sprees]
messages = 1
